# BY GOD'S GRACE ALONE

key : val
AUGMENTATION: True
IMAGE_SIZE : [224,224,3] # with respect to the VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS : 4
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01                                                                    
